# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-03 03:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Referencia', models.CharField(max_length=50)),
                ('Matricula', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Autos',
            },
        ),
        migrations.AlterModelOptions(
            name='tipo_auto',
            options={'verbose_name_plural': 'Tipo Autos'},
        ),
        migrations.AddField(
            model_name='auto',
            name='Tipo_auto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autos.Tipo_Auto'),
        ),
    ]
