# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-03 03:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autos', '0002_auto_20181002_2213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lavado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Jabon', models.FloatField(max_length=50)),
                ('Agua', models.FloatField(max_length=50)),
                ('Tiempo', models.IntegerField(max_length=50)),
                ('Auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autos.Auto')),
            ],
            options={
                'verbose_name_plural': 'Lavados',
            },
        ),
    ]
